# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-test
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

patent_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: ../data/patent/test.tsv
  question_col: 0
  answers_col: 1
  id_col: 2
